FROM python:3.9-slim

WORKDIR /app

COPY monitoring/monitor.py .
COPY data /app/data
COPY monitoring/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "monitoring/monitor.py"]
