# Dockerfile.api — pour FastAPI
FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python -m nltk.downloader punkt stopwords wordnet

EXPOSE 8000

ENV PYTHONPATH=/app/src

CMD ["uvicorn", "fast_api:app", "--host", "0.0.0.0", "--port", "8000"]
