epochs: 1
batch_size: 32
learning_rate: 0.001
max_words: 10000
max_sequence_length: 10
embedding_dim: 128
lstm_units: 128
dropout_rate: 0.5
image_size: 224
num_classes: 27
use_mps: false  # Mettre à true pour utiliser MPS, false pour forcer CPU / CUDA