version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitoring-network

  evidently:
    build:
      context: ./evidently
    ports:
      - "8050:8050"
    restart: always
    networks:
      - monitoring-network

  node-exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - "9100:9100"
    restart: always
    networks:
      - monitoring-network

networks:
  monitoring-network:

volumes:
  grafana-storage: