tracking_server:
  uri: http://localhost:5001
  
artifact_store:
  location: /mlflow/artifacts
  
backend_store:
  sqlite_uri: sqlite:///mlflow/mlflow.db

experiments:
  rakuten_classification:
    name: rakuten-classification
    description: "Classification d'articles e-commerce Rakuten"
    artifact_location: /mlflow/artifacts/rakuten-classification
    
  rakuten_evaluation:
    name: rakuten-classification-evaluation
    description: "Evaluation du modèle de classification Rakuten"
    artifact_location: /mlflow/artifacts/rakuten-classification-evaluation
    
  rakuten_api:
    name: rakuten-prediction-api
    description: "Prédictions de l'API du modèle Rakuten"
    artifact_location: /mlflow/artifacts/rakuten-prediction-api
